language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

env:
    global:
        - PHPUNIT_FLAGS="-v"

matrix:
    fast_finish: true
    include:
        # Minimum supported dependencies with min and max PHP version
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

        # Latest supported dependencies with each PHP version
        - php: 7.1
        - php: 7.2
        - php: 7.3
          env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-clover=coverage.clover"

        # Install all SF components in the same major version, see https://github.com/dunglas/symfony-lock
        - php: 7.3
          env: SYMFONY_VERSION="^4"

before_install:
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi

install:
    # To be removed when this issue will be resolved: https://github.com/composer/composer/issues/5355
    - if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --prefer-dist --no-interaction --prefer-stable --quiet; fi
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update dunglas/symfony-lock=$SYMFONY_VERSION; fi;
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
    - vendor/bin/phpunit ${PHPUNIT_FLAGS} tests